/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Scenario = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'parameters' : IDL.Record({
    'temperature' : IDL.Float64,
    'holdTime' : IDL.Float64,
    'coolingRate' : IDL.Float64,
    'feedRate' : IDL.Float64,
    'pressure' : IDL.Float64,
  }),
});
export const GoldenSignature = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'parameters' : IDL.Record({
    'temperature' : IDL.Float64,
    'holdTime' : IDL.Float64,
    'coolingRate' : IDL.Float64,
    'feedRate' : IDL.Float64,
    'pressure' : IDL.Float64,
  }),
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
  'objectives' : IDL.Record({
    'carbonKg' : IDL.Float64,
    'energyKwh' : IDL.Float64,
    'qualityPct' : IDL.Float64,
    'yieldPct' : IDL.Float64,
    'performancePct' : IDL.Float64,
  }),
});
export const BatchRecord = IDL.Record({
  'id' : IDL.Text,
  'maintenanceAlertProb' : IDL.Float64,
  'carbonKg' : IDL.Float64,
  'temperature' : IDL.Float64,
  'holdTime' : IDL.Float64,
  'coolingRate' : IDL.Float64,
  'feedRate' : IDL.Float64,
  'energyKwh' : IDL.Float64,
  'pressure' : IDL.Float64,
  'qualityPct' : IDL.Float64,
  'timestamp' : IDL.Int,
  'deviationScore' : IDL.Float64,
  'materialType' : IDL.Text,
  'machineId' : IDL.Text,
  'riskScore' : IDL.Float64,
  'yieldPct' : IDL.Float64,
  'batchSize' : IDL.Float64,
  'performancePct' : IDL.Float64,
});

export const idlService = IDL.Service({
  'acceptRecommendation' : IDL.Func([IDL.Text], [], []),
  'compareScenarios' : IDL.Func(
      [IDL.Text, IDL.Text],
      [Scenario, Scenario],
      ['query'],
    ),
  'createSignature' : IDL.Func([GoldenSignature], [], []),
  'deleteSignature' : IDL.Func([IDL.Text], [], []),
  'getBatchById' : IDL.Func([IDL.Text], [BatchRecord], ['query']),
  'getBatches' : IDL.Func([], [IDL.Vec(BatchRecord)], ['query']),
  'getScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'getSignatureById' : IDL.Func([IDL.Text], [GoldenSignature], ['query']),
  'getSignatures' : IDL.Func([], [IDL.Vec(GoldenSignature)], ['query']),
  'modifyRecommendation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectRecommendation' : IDL.Func([IDL.Text], [], []),
  'saveScenario' : IDL.Func([IDL.Text, Scenario], [], []),
  'storeBatch' : IDL.Func([BatchRecord], [], []),
  'updateSignatureStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Scenario = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'parameters' : IDL.Record({
      'temperature' : IDL.Float64,
      'holdTime' : IDL.Float64,
      'coolingRate' : IDL.Float64,
      'feedRate' : IDL.Float64,
      'pressure' : IDL.Float64,
    }),
  });
  const GoldenSignature = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'parameters' : IDL.Record({
      'temperature' : IDL.Float64,
      'holdTime' : IDL.Float64,
      'coolingRate' : IDL.Float64,
      'feedRate' : IDL.Float64,
      'pressure' : IDL.Float64,
    }),
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
    'objectives' : IDL.Record({
      'carbonKg' : IDL.Float64,
      'energyKwh' : IDL.Float64,
      'qualityPct' : IDL.Float64,
      'yieldPct' : IDL.Float64,
      'performancePct' : IDL.Float64,
    }),
  });
  const BatchRecord = IDL.Record({
    'id' : IDL.Text,
    'maintenanceAlertProb' : IDL.Float64,
    'carbonKg' : IDL.Float64,
    'temperature' : IDL.Float64,
    'holdTime' : IDL.Float64,
    'coolingRate' : IDL.Float64,
    'feedRate' : IDL.Float64,
    'energyKwh' : IDL.Float64,
    'pressure' : IDL.Float64,
    'qualityPct' : IDL.Float64,
    'timestamp' : IDL.Int,
    'deviationScore' : IDL.Float64,
    'materialType' : IDL.Text,
    'machineId' : IDL.Text,
    'riskScore' : IDL.Float64,
    'yieldPct' : IDL.Float64,
    'batchSize' : IDL.Float64,
    'performancePct' : IDL.Float64,
  });
  
  return IDL.Service({
    'acceptRecommendation' : IDL.Func([IDL.Text], [], []),
    'compareScenarios' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Scenario, Scenario],
        ['query'],
      ),
    'createSignature' : IDL.Func([GoldenSignature], [], []),
    'deleteSignature' : IDL.Func([IDL.Text], [], []),
    'getBatchById' : IDL.Func([IDL.Text], [BatchRecord], ['query']),
    'getBatches' : IDL.Func([], [IDL.Vec(BatchRecord)], ['query']),
    'getScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'getSignatureById' : IDL.Func([IDL.Text], [GoldenSignature], ['query']),
    'getSignatures' : IDL.Func([], [IDL.Vec(GoldenSignature)], ['query']),
    'modifyRecommendation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectRecommendation' : IDL.Func([IDL.Text], [], []),
    'saveScenario' : IDL.Func([IDL.Text, Scenario], [], []),
    'storeBatch' : IDL.Func([BatchRecord], [], []),
    'updateSignatureStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };