/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BatchRecord {
  'id' : string,
  'maintenanceAlertProb' : number,
  'carbonKg' : number,
  'temperature' : number,
  'holdTime' : number,
  'coolingRate' : number,
  'feedRate' : number,
  'energyKwh' : number,
  'pressure' : number,
  'qualityPct' : number,
  'timestamp' : bigint,
  'deviationScore' : number,
  'materialType' : string,
  'machineId' : string,
  'riskScore' : number,
  'yieldPct' : number,
  'batchSize' : number,
  'performancePct' : number,
}
export interface GoldenSignature {
  'id' : string,
  'status' : string,
  'name' : string,
  'createdAt' : bigint,
  'parameters' : {
    'temperature' : number,
    'holdTime' : number,
    'coolingRate' : number,
    'feedRate' : number,
    'pressure' : number,
  },
  'updatedAt' : bigint,
  'category' : string,
  'objectives' : {
    'carbonKg' : number,
    'energyKwh' : number,
    'qualityPct' : number,
    'yieldPct' : number,
    'performancePct' : number,
  },
}
export interface Scenario {
  'id' : string,
  'name' : string,
  'parameters' : {
    'temperature' : number,
    'holdTime' : number,
    'coolingRate' : number,
    'feedRate' : number,
    'pressure' : number,
  },
}
export interface _SERVICE {
  'acceptRecommendation' : ActorMethod<[string], undefined>,
  'compareScenarios' : ActorMethod<[string, string], [Scenario, Scenario]>,
  'createSignature' : ActorMethod<[GoldenSignature], undefined>,
  'deleteSignature' : ActorMethod<[string], undefined>,
  'getBatchById' : ActorMethod<[string], BatchRecord>,
  'getBatches' : ActorMethod<[], Array<BatchRecord>>,
  'getScenarios' : ActorMethod<[], Array<Scenario>>,
  'getSignatureById' : ActorMethod<[string], GoldenSignature>,
  'getSignatures' : ActorMethod<[], Array<GoldenSignature>>,
  'modifyRecommendation' : ActorMethod<[string, string], undefined>,
  'rejectRecommendation' : ActorMethod<[string], undefined>,
  'saveScenario' : ActorMethod<[string, Scenario], undefined>,
  'storeBatch' : ActorMethod<[BatchRecord], undefined>,
  'updateSignatureStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];