/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GoldenSignature {
    id: string;
    status: string;
    name: string;
    createdAt: bigint;
    parameters: {
        temperature: number;
        holdTime: number;
        coolingRate: number;
        feedRate: number;
        pressure: number;
    };
    updatedAt: bigint;
    category: string;
    objectives: {
        carbonKg: number;
        energyKwh: number;
        qualityPct: number;
        yieldPct: number;
        performancePct: number;
    };
}
export interface BatchRecord {
    id: string;
    maintenanceAlertProb: number;
    carbonKg: number;
    temperature: number;
    holdTime: number;
    coolingRate: number;
    feedRate: number;
    energyKwh: number;
    pressure: number;
    qualityPct: number;
    timestamp: bigint;
    deviationScore: number;
    materialType: string;
    machineId: string;
    riskScore: number;
    yieldPct: number;
    batchSize: number;
    performancePct: number;
}
export interface Scenario {
    id: string;
    name: string;
    parameters: {
        temperature: number;
        holdTime: number;
        coolingRate: number;
        feedRate: number;
        pressure: number;
    };
}
export interface backendInterface {
    acceptRecommendation(id: string): Promise<void>;
    compareScenarios(id1: string, id2: string): Promise<[Scenario, Scenario]>;
    createSignature(signature: GoldenSignature): Promise<void>;
    deleteSignature(id: string): Promise<void>;
    getBatchById(id: string): Promise<BatchRecord>;
    getBatches(): Promise<Array<BatchRecord>>;
    getScenarios(): Promise<Array<Scenario>>;
    getSignatureById(id: string): Promise<GoldenSignature>;
    getSignatures(): Promise<Array<GoldenSignature>>;
    modifyRecommendation(id: string, newMessage: string): Promise<void>;
    rejectRecommendation(id: string): Promise<void>;
    saveScenario(name: string, params: Scenario): Promise<void>;
    storeBatch(batch: BatchRecord): Promise<void>;
    updateSignatureStatus(id: string, status: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptRecommendation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptRecommendation(arg0);
            return result;
        }
    }
    async compareScenarios(arg0: string, arg1: string): Promise<[Scenario, Scenario]> {
        if (this.processError) {
            try {
                const result = await this.actor.compareScenarios(arg0, arg1);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareScenarios(arg0, arg1);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async createSignature(arg0: GoldenSignature): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSignature(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSignature(arg0);
            return result;
        }
    }
    async deleteSignature(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSignature(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSignature(arg0);
            return result;
        }
    }
    async getBatchById(arg0: string): Promise<BatchRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchById(arg0);
            return result;
        }
    }
    async getBatches(): Promise<Array<BatchRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatches();
            return result;
        }
    }
    async getScenarios(): Promise<Array<Scenario>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScenarios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScenarios();
            return result;
        }
    }
    async getSignatureById(arg0: string): Promise<GoldenSignature> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignatureById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignatureById(arg0);
            return result;
        }
    }
    async getSignatures(): Promise<Array<GoldenSignature>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignatures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignatures();
            return result;
        }
    }
    async modifyRecommendation(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifyRecommendation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifyRecommendation(arg0, arg1);
            return result;
        }
    }
    async rejectRecommendation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRecommendation(arg0);
            return result;
        }
    }
    async saveScenario(arg0: string, arg1: Scenario): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScenario(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScenario(arg0, arg1);
            return result;
        }
    }
    async storeBatch(arg0: BatchRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeBatch(arg0);
            return result;
        }
    }
    async updateSignatureStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignatureStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignatureStatus(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
